services:
  sub-converter:
    restart: unless-stopped
    image: dev2people/proxy-sub-transformer-rust:latest
    ports:
      - "29081:8189"
    volumes:
      - ./data:/app/data
      #- ./config:/app/config
    environment:
      - DATABASE_URL=sqlite:///app/data/sub.db?mode=rwc
      - RUST_LOG=info
  # 通过http://clash-speedtest:8080/speedtest_append_name访问测速服务,过滤掉超时的节点
  clash-speedtest:
    restart: unless-stopped
    image: dev2people/clashsub-tools-clashspeedtest-v0
    # ports:
    #   - 18080:8080
    environment:
      - AUTH_KEY=sdhadhasdkjhbwe323498bdfsd9873r3yhasdbedfh9321r